{
  throw new AssertionFailure("Add a <join> in a second pass");
}
