{
  throw new AssertionFailure("insert statement returns generated value");
}
