{
  try {
    return method.invoke(target,(Object[])null);
  }
 catch (  InvocationTargetException ite) {
    throw new PropertyAccessException(ite,"Exception occurred inside",false,clazz,propertyName);
  }
catch (  IllegalAccessException iae) {
    throw new PropertyAccessException(iae,"IllegalAccessException occurred while calling",false,clazz,propertyName);
  }
catch (  IllegalArgumentException iae) {
    LOG.illegalPropertyGetterArgument(clazz.getName(),propertyName);
    throw new PropertyAccessException(iae,"IllegalArgumentException occurred calling",false,clazz,propertyName);
  }
}
