{
  try {
    return method.invoke(target,null);
  }
 catch (  InvocationTargetException ite) {
    throw new PropertyAccessException(ite,"Exception occurred inside",false,clazz,propertyName);
  }
catch (  IllegalAccessException iae) {
    throw new PropertyAccessException(iae,"IllegalAccessException occurred while calling",false,clazz,propertyName);
  }
catch (  IllegalArgumentException iae) {
    log.error("IllegalArgumentException in class: " + clazz.getName() + ", getter method of property: "+ propertyName);
    throw new PropertyAccessException(iae,"IllegalArgumentException occurred calling",false,clazz,propertyName);
  }
}
