{
  if (errorOnAfter) {
    throw new RuntimeException("throwing requested error on afterCompletion");
  }
}
